// Code generated by cmd/contractgen from api/openapi.json; DO NOT EDIT.
import Foundation

enum APIPath {
    static func ackVerdict(id: String) -> String { "/v1/verdicts/\(id)/ack" }
    static func addHarvest(slug: String) -> String { "/v1/plants/\(slug)/harvests" }
    static let addHouseholdNote = "/v1/notes"
    static func addObservation(slug: String) -> String { "/v1/plants/\(slug)/observations" }
    static func addPlantNote(slug: String) -> String { "/v1/plants/\(slug)/notes" }
    static func answerQuestion(id: String) -> String { "/v1/questions/\(id)/answer" }
    static func archivePlant(slug: String) -> String { "/v1/plants/\(slug)" }
    static let ask = "/v1/ask"
    static func askPlant(slug: String) -> String { "/v1/plants/\(slug)/ask" }
    static func calibrateSensor(id: String) -> String { "/v1/sensors/\(id)" }
    static func clearModelAssignment(job: String) -> String { "/v1/model-assignments/\(job)" }
    static let coldWatch = "/v1/cold-watch"
    static func completeReminder(id: String) -> String { "/v1/reminders/\(id)/complete" }
    static func completeVerdict(id: String) -> String { "/v1/verdicts/\(id)/complete" }
    static let createAway = "/v1/away"
    static let createOwnerUpdate = "/v1/owner-update"
    static let createPlant = "/v1/plants"
    static let createPlantFromPhoto = "/v1/plants/from-photo"
    static func createPostmortem(slug: String) -> String { "/v1/plants/\(slug)/postmortem" }
    static let createQuestion = "/v1/questions"
    static func deleteAway(id: String) -> String { "/v1/away/\(id)" }
    static func deleteNote(id: String) -> String { "/v1/notes/\(id)" }
    static func deleteReminder(slug: String, kind: String) -> String { "/v1/plants/\(slug)/reminders/\(kind)" }
    static func getPlant(slug: String) -> String { "/v1/plants/\(slug)" }
    static func getTimeline(slug: String) -> String { "/v1/plants/\(slug)/timeline" }
    static let health = "/healthz"
    static let identify = "/v1/identify"
    static let linkSensor = "/v1/sensors"
    static let listAway = "/v1/away"
    static let listChoices = "/v1/choices"
    static let listHarvests = "/v1/harvests"
    static let listHomeAssistantEntities = "/v1/home-assistant/entities"
    static let listHouseholdNotes = "/v1/notes"
    static let listModelAssignments = "/v1/model-assignments"
    static let listModels = "/v1/models"
    static func listObservations(slug: String) -> String { "/v1/plants/\(slug)/observations" }
    static func listPlantHarvests(slug: String) -> String { "/v1/plants/\(slug)/harvests" }
    static func listPlantNotes(slug: String) -> String { "/v1/plants/\(slug)/notes" }
    static let listPlants = "/v1/plants"
    static let listPostmortems = "/v1/postmortems"
    static let listQuestions = "/v1/questions"
    static func listReminders(slug: String) -> String { "/v1/plants/\(slug)/reminders" }
    static let listSensors = "/v1/sensors"
    static let registerPushDevice = "/v1/push-devices"
    static func setModelAssignment(job: String) -> String { "/v1/model-assignments/\(job)" }
    static func setReminder(slug: String) -> String { "/v1/plants/\(slug)/reminders" }
    static let shelter = "/v1/shelter"
    static let today = "/v1/today"
    static let unshelter = "/v1/unshelter"
    static func updateAway(id: String) -> String { "/v1/away/\(id)" }
    static func updateNote(id: String) -> String { "/v1/notes/\(id)" }
    static func updatePlant(slug: String) -> String { "/v1/plants/\(slug)" }
    static func uploadPhoto(slug: String) -> String { "/v1/plants/\(slug)/photos" }
}

enum AIJob: String, FallbackDecodable, CaseIterable {
    case assess
    case identify
    case consult
    case ask
    case postmortem
    case ownerUpdate = "owner_update"
    case unknown

    static let fallback = AIJob.unknown
}

struct APIErrorBody: Codable, Sendable {
    let code: String?
    let error: String
    let requestId: String?

    enum CodingKeys: String, CodingKey {
        case code
        case error
        case requestId = "request_id"
    }
}

enum LightExposure: String, FallbackDecodable, CaseIterable {
    case direct
    case brightIndirect = "bright_indirect"
    case medium
    case low
    case unknown

    static let fallback = LightExposure.unknown
}

enum ObservationKind: String, FallbackDecodable, CaseIterable {
    case watered
    case misted
    case repotted
    case fertilized
    case pruned
    case harvested
    case moved
    case symptom
    case note
    case died
    case unknown

    static let fallback = ObservationKind.unknown
}

enum ObservationSource: String, FallbackDecodable, CaseIterable {
    case app
    case agent
    case automation
    case unknown

    static let fallback = ObservationSource.unknown
}

enum PlantAccessibility: String, FallbackDecodable, CaseIterable {
    case easy
    case awkward
    case hard
    case unknown

    static let fallback = PlantAccessibility.unknown
}

enum PlantDomain: String, FallbackDecodable, CaseIterable {
    case houseplant
    case edibleIndoor = "edible_indoor"
    case edibleOutdoor = "edible_outdoor"
    case unknown

    static let fallback = PlantDomain.unknown
}

enum PlantStatus: String, FallbackDecodable, CaseIterable {
    case alive
    case struggling
    case dormant
    case dead
    case gone
    case unknown

    static let fallback = PlantStatus.unknown
}

enum SensorRole: String, FallbackDecodable, CaseIterable {
    case soilMoisture = "soil_moisture"
    case ambientTemp = "ambient_temp"
    case ambientHumidity = "ambient_humidity"
    case illuminance
    case unknown

    static let fallback = SensorRole.unknown
}

enum VerdictAction: String, FallbackDecodable, CaseIterable {
    case none
    case water
    case check
    case urgent
    case harvest
    case unknown

    static let fallback = VerdictAction.unknown
}

enum WateringMethod: String, FallbackDecodable, CaseIterable {
    case letpot
    case hand
    case unknown

    static let fallback = WateringMethod.unknown
}

