// Command contractgen generates the pieces of the Go and Swift HTTP clients
// that should never be handwritten twice. The OpenAPI document remains the
// source of truth; presentation labels and view behavior stay handwritten.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

type operation struct {
	OperationID string `json:"operationId"`
}

type property struct {
	Type string `json:"type"`
}

type schema struct {
	Type       string              `json:"type"`
	Enum       []string            `json:"enum"`
	Required   []string            `json:"required"`
	Properties map[string]property `json:"properties"`
	SwiftName  string              `json:"x-swift-name"`
}

type document struct {
	Paths      map[string]map[string]operation `json:"paths"`
	Components struct {
		Schemas map[string]schema `json:"schemas"`
	} `json:"components"`
}

type route struct {
	Method      string
	Path        string
	OperationID string
	Params      []string
}

var parameterPattern = regexp.MustCompile(`\{([A-Za-z0-9_]+)\}`)

func main() {
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	raw, err := os.ReadFile(filepath.Join(*root, "api", "openapi.json"))
	must(err)
	var doc document
	must(json.Unmarshal(raw, &doc))

	routes := collectRoutes(doc)
	must(writeGo(filepath.Join(*root, "internal", "api", "contract_generated.go"), routes))
	must(writeSwift(filepath.Join(*root, "ios", "Planty", "Networking", "APIContract.generated.swift"), routes, doc.Components.Schemas))
}

func collectRoutes(doc document) []route {
	var out []route
	for path, methods := range doc.Paths {
		for method, op := range methods {
			if op.OperationID == "" {
				continue
			}
			matches := parameterPattern.FindAllStringSubmatch(path, -1)
			params := make([]string, 0, len(matches))
			for _, match := range matches {
				params = append(params, match[1])
			}
			out = append(out, route{
				Method: strings.ToUpper(method), Path: path,
				OperationID: op.OperationID, Params: params,
			})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].OperationID < out[j].OperationID })
	return out
}

func writeGo(path string, routes []route) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/contractgen from api/openapi.json; DO NOT EDIT.\n")
	b.WriteString("package api\n\nconst (\n")
	for _, route := range routes {
		fmt.Fprintf(&b, "\troute%s = %q\n", upperFirst(route.OperationID), route.Method+" "+route.Path)
	}
	b.WriteString(")\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func writeSwift(path string, routes []route, schemas map[string]schema) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/contractgen from api/openapi.json; DO NOT EDIT.\n")
	b.WriteString("import Foundation\n\n")
	b.WriteString("enum APIPath {\n")
	for _, route := range routes {
		if len(route.Params) == 0 {
			fmt.Fprintf(&b, "    static let %s = %q\n", route.OperationID, route.Path)
			continue
		}
		params := make([]string, 0, len(route.Params))
		for _, p := range route.Params {
			params = append(params, p+": String")
		}
		expression := route.Path
		for _, p := range route.Params {
			expression = strings.ReplaceAll(expression, "{"+p+"}", "\\("+p+")")
		}
		fmt.Fprintf(&b, "    static func %s(%s) -> String { %q }\n", route.OperationID, strings.Join(params, ", "), expression)
	}
	b.WriteString("}\n\n")

	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		s := schemas[name]
		swiftName := s.SwiftName
		if swiftName == "" {
			swiftName = name
		}
		switch {
		case s.Type == "string" && len(s.Enum) > 0:
			fmt.Fprintf(&b, "enum %s: String, FallbackDecodable, CaseIterable {\n", swiftName)
			for _, raw := range s.Enum {
				caseName := swiftIdentifier(raw)
				if caseName == raw {
					fmt.Fprintf(&b, "    case %s\n", caseName)
				} else {
					fmt.Fprintf(&b, "    case %s = %q\n", caseName, raw)
				}
			}
			b.WriteString("    case unknown\n\n")
			fmt.Fprintf(&b, "    static let fallback = %s.unknown\n", swiftName)
			b.WriteString("}\n\n")
		case s.Type == "object":
			writeSwiftObject(&b, swiftName, s)
		}
	}
	return os.WriteFile(path, b.Bytes(), 0o644)
}

func writeSwiftObject(b *bytes.Buffer, name string, s schema) {
	required := make(map[string]bool, len(s.Required))
	for _, field := range s.Required {
		required[field] = true
	}
	fields := make([]string, 0, len(s.Properties))
	for field := range s.Properties {
		fields = append(fields, field)
	}
	sort.Strings(fields)
	fmt.Fprintf(b, "struct %s: Codable, Sendable {\n", name)
	for _, field := range fields {
		typeName := "String"
		if s.Properties[field].Type != "string" {
			continue
		}
		if !required[field] {
			typeName += "?"
		}
		fmt.Fprintf(b, "    let %s: %s\n", swiftIdentifier(field), typeName)
	}
	needsKeys := false
	for _, field := range fields {
		if swiftIdentifier(field) != field {
			needsKeys = true
			break
		}
	}
	if needsKeys {
		b.WriteString("\n    enum CodingKeys: String, CodingKey {\n")
		for _, field := range fields {
			name := swiftIdentifier(field)
			if name == field {
				fmt.Fprintf(b, "        case %s\n", name)
			} else {
				fmt.Fprintf(b, "        case %s = %q\n", name, field)
			}
		}
		b.WriteString("    }\n")
	}
	b.WriteString("}\n\n")
}

func swiftIdentifier(raw string) string {
	parts := strings.FieldsFunc(raw, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	if len(parts) == 0 {
		return "value"
	}
	name := strings.ToLower(parts[0])
	for _, part := range parts[1:] {
		name += upperFirst(strings.ToLower(part))
	}
	if len(name) > 0 && unicode.IsDigit(rune(name[0])) {
		name = "value" + upperFirst(name)
	}
	return name
}

func upperFirst(value string) string {
	if value == "" {
		return value
	}
	r := []rune(value)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
